version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::381492125278:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-Gxy7gY8A9uUP"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::381492125278:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-6nXuBFOcX4wx"
cloudformation_execution_role = "arn:aws:iam::381492125278:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-mOceLW88ZLea"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-hsmmsew3qcah"
image_repository = ""
region = "eu-north-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::767976552522:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-UYv2HRU7eIYv"
cloudformation_execution_role = "arn:aws:iam::767976552522:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-m2Ww5BKox2LU"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-qm5k1tqxwmbi"
image_repository = ""
region = "eu-north-1"
